import type { Metadata } from "next";
import "./globals.css";
import { SidebarDemo } from "@/components/custom/custom_sidebar";
import { ThemeProvider } from "@/components/custom/theme-provider";
import UserProvider from "@/components/custom/UserProvider";
import QueryProvider from "@/components/custom/QueryProvider";
import { Toaster } from "sonner";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          {/* <script
            crossOrigin="anonymous"
            src="//unpkg.com/react-scan/dist/auto.global.js"
          /> */}
        </head>

        <body className={`antialiased bg-accent/50 dark:bg-accent/30`}>
          <header className="absolute z-20 top-2 right-2 p-2">
            <SignedIn>
              <UserButton
                appearance={{
                  elements: {
                    userButtonAvatarBox: {
                      // This is an example class, find the actual one by inspecting
                      width: "38px", // Example: Increase width
                      height: "38px", // Example: Increase height
                    },
                  },
                }}
              />
            </SignedIn>
          </header>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <UserProvider>
                <div className="flex h-screen">
                  <div className="fixed flex-shrink-0 z-50">
                    <SidebarDemo />
                  </div>
                  <main className="flex w-full overflow-auto ml-16">
                    {children}
                  </main>
                </div>
              </UserProvider>
            </ThemeProvider>
          </QueryProvider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
